trigger:
- main

pool:
  # vmImage: 'windows-latest'
  name: 'localDesktopMachine'

variables:
  solution: 'dotnet-app-mvc.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  outputDir: '$(build.artifactStagingDirectory)'
  defaultDir: '$(System.DefaultWorkingDirectory)'

stages:
  # build dotnet app mvc
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildNetCoreApp
        displayName: Build .Net Core app
        steps:

          # install dotnet v8
          - task: UseDotNet@2
            displayName: 'Install .net core v8'
            inputs:
              packageType: 'sdk'
              version: '8.0.424'

          # dotnet restore
          - task: DotNetCoreCLI@2
            displayName: 'Restore Dependencies'
            inputs:
              command: 'restore'
              projects: '$(solution)'

          # dotnet build
          - task: DotNetCoreCLI@2
            displayName: 'Build Proyect'
            inputs:
              command: 'build'
              projects: '$(solution)'

          # dotnet publish
          - task: DotNetCoreCLI@2
            displayName: 'Create dotnet-app-core.zip'
            inputs:
              command: 'publish'
              publishWebProjects: true
              arguments: '--configuration $(buildConfiguration) --output $(outputDir)'

          # publish build artifact
          - task: PublishBuildArtifacts@1
            displayName: 'Publish dotnet-app-core.zip'
            inputs:
              PathtoPublish: '$(outputDir)'
              ArtifactName: 'drop'
              # publishLocation: 'Container'

          # notification successfully!
          - script: echo Build completed successfully!!!
            displayName: 'Notification, Build Status'

  - stage: Deploy
    displayName: Deploy Stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: 'Deploy to Azure App Service'
        steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Artifact (dotnet-app-core.zip) from drop folder'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(defaultDir)'

          - task: AzureRmWebAppDeployment@5
            displayName: 'Deploy in Azure App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'azsubscription'
              appType: 'webApp'
              WebAppName: 'dotnet-core-app'
              deployToSlotOrASE: true
              ResourceGroupName: 'bycentinel-example-group'
              SlotName: 'production'
              packageForLinux: '$(defaultDir)/**/*.zip'

          - script: echo Deployment to Azure App Service completed!
            displayName: 'Notification, Deployment Status'